ALTER TABLE "Business"
ADD CONSTRAINT "Business_ownerDependenceRating_check" CHECK ("ownerDependenceRating" IS NULL OR "ownerDependenceRating" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_recurringRevenueRating_check" CHECK ("recurringRevenueRating" IS NULL OR "recurringRevenueRating" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_transferabilityRating_check" CHECK ("transferabilityRating" IS NULL OR "transferabilityRating" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_scheduleControlFitRating_check" CHECK ("scheduleControlFitRating" IS NULL OR "scheduleControlFitRating" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_brotherOperatorFitRating_check" CHECK ("brotherOperatorFitRating" IS NULL OR "brotherOperatorFitRating" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_aiResistanceScore_check" CHECK ("aiResistanceScore" IS NULL OR "aiResistanceScore" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_keepDayJobFit_check" CHECK ("keepDayJobFit" IS NULL OR "keepDayJobFit" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_quitDayJobFit_check" CHECK ("quitDayJobFit" IS NULL OR "quitDayJobFit" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_financeabilityRating_check" CHECK ("financeabilityRating" IS NULL OR "financeabilityRating" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_operatorSkillDependency_check" CHECK ("operatorSkillDependency" IS NULL OR "operatorSkillDependency" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_licenseDependency_check" CHECK ("licenseDependency" IS NULL OR "licenseDependency" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_afterHoursBurden_check" CHECK ("afterHoursBurden" IS NULL OR "afterHoursBurden" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_capexRisk_check" CHECK ("capexRisk" IS NULL OR "capexRisk" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_regretIfWrongScore_check" CHECK ("regretIfWrongScore" IS NULL OR "regretIfWrongScore" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_dataConfidenceScore_check" CHECK ("dataConfidenceScore" IS NULL OR "dataConfidenceScore" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_staleListingRisk_check" CHECK ("staleListingRisk" IS NULL OR "staleListingRisk" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_keyPersonRisk_check" CHECK ("keyPersonRisk" IS NULL OR "keyPersonRisk" BETWEEN 1 AND 5),
ADD CONSTRAINT "Business_recurringRevenuePercent_check" CHECK ("recurringRevenuePercent" IS NULL OR ("recurringRevenuePercent" >= 0 AND "recurringRevenuePercent" <= 100));
